// <auto-generated />
using System;
using CustomerMaster.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomerMaster.Migrations
{
    [DbContext(typeof(CustomerMasterContext))]
    partial class CustomerMasterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustomerMaster.Models.TblDbCustomers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AcctNumber");

                    b.Property<decimal?>("AllowedOverRunPercentage");

                    b.Property<string>("BillToEmailAddress");

                    b.Property<int?>("CompanyId");

                    b.Property<int?>("CustActive");

                    b.Property<string>("CustAlpha");

                    b.Property<string>("CustBillAddr2");

                    b.Property<string>("CustBillAddress");

                    b.Property<string>("CustBillCity");

                    b.Property<string>("CustBillState");

                    b.Property<string>("CustBillZipCode");

                    b.Property<string>("CustContact");

                    b.Property<string>("CustFax");

                    b.Property<string>("CustName");

                    b.Property<string>("CustPhone");

                    b.Property<string>("CustPlant");

                    b.Property<string>("CustomerTerms");

                    b.Property<bool?>("Deleted");

                    b.Property<string>("InsideRep");

                    b.Property<int?>("MasterAcctNumber");

                    b.Property<string>("OutsideRep");

                    b.Property<int?>("ShipToCheck");

                    b.Property<DateTime?>("UpdatedDateTime");

                    b.Property<string>("UpdatedUser");

                    b.HasKey("Id");

                    b.ToTable("TblDb_Customers");
                });

            modelBuilder.Entity("CustomerMaster.Models.TblDbCustomersShipTo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AcctNumber");

                    b.Property<int?>("CompanyId");

                    b.Property<string>("CustAlpha");

                    b.Property<string>("CustContact");

                    b.Property<string>("CustFax");

                    b.Property<string>("CustId");

                    b.Property<string>("CustName");

                    b.Property<string>("CustPhone");

                    b.Property<string>("CustPlant");

                    b.Property<int?>("CustShipActive");

                    b.Property<string>("CustShipAddr2");

                    b.Property<string>("CustShipAddress");

                    b.Property<string>("CustShipCity");

                    b.Property<string>("CustShipName");

                    b.Property<string>("CustShipState");

                    b.Property<string>("CustShipZipCode");

                    b.Property<bool?>("Deleted");

                    b.Property<string>("InsideRep");

                    b.Property<string>("OutsideRep");

                    b.HasKey("Id");

                    b.ToTable("TblDb_Customers_ShipTo");
                });

            modelBuilder.Entity("CustomerMaster.Models.TblOrdersComments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AcctNumber")
                        .HasColumnName("AcctNumber")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("CompanyId");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("Created_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedUser")
                        .HasColumnName("CreatedUser")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedWorkStation")
                        .HasColumnName("CreatedWorkStation")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustId")
                        .HasColumnName("CustId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UpdatedDateTime")
                        .HasColumnName("UpdatedDateTime")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UpdatedUser")
                        .HasColumnName("UpdatedUser")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TblOrders_Comments");
                });

            modelBuilder.Entity("CustomerMaster.Models.TblOrdersCommentsAudit", b =>
                {
                    b.Property<int>("TblOrdersCommentsAuditID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AcctNumber")
                        .HasColumnName("AcctNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("AuditDateTime");

                    b.Property<string>("AuditOperation")
                        .HasMaxLength(50);

                    b.Property<string>("AuditUser")
                        .HasMaxLength(50);

                    b.Property<string>("Comment")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("CompanyId");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("Created_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedUser")
                        .HasColumnName("CreatedUser")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedWorkStation")
                        .HasColumnName("CreatedWorkStation")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustId")
                        .HasColumnName("CustId")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Id");

                    b.Property<string>("UpdatedDateTime")
                        .HasColumnName("UpdatedDateTime")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UpdatedUser")
                        .HasColumnName("UpdatedUser")
                        .HasColumnType("varchar(50)");

                    b.HasKey("TblOrdersCommentsAuditID");

                    b.ToTable("TblOrders_CommentsAudit");
                });

            modelBuilder.Entity("CustomerMaster.Models.TblOrdersInsideRep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Initials");

                    b.Property<string>("RepName");

                    b.HasKey("Id");

                    b.ToTable("tblOrders_InsideRep");
                });

            modelBuilder.Entity("CustomerMaster.Models.TblOrdersOutsideRep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Initials");

                    b.Property<string>("RepName");

                    b.HasKey("Id");

                    b.ToTable("tblOrders_OutsideRep");
                });

            modelBuilder.Entity("CustomerMaster.Models.TblSysCompany", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName");

                    b.HasKey("CompanyId");

                    b.ToTable("TblSys_Company");
                });
#pragma warning restore 612, 618
        }
    }
}
